### ISSUE TITLE
usesophus中的问题

### ISSUE THREAD

**Issue by zssjh** [Ewenwan/MVision#1]
**注意，不是旋转向量的三个坐标值，有点像欧拉角构造。因为假设是旋转向量的三个坐标值构造的话，那么Sophus::SO3 SO3_111( 1, 1, 1 );构造输出出来的应该也是( 1, 1, 1 ) 。**
你好，请问上面这句话是什么意思，你的意思是so3输出的值就是旋转向量吗，因为和构造所用的三个值不一样所以构造的三个数不是旋转向量的三个坐标值？

**Comment by Ewenwan** [comment]
可参考这里 https://blog.csdn.net/x_r_su/article/details/52749616
so3其实是 旋转矩阵R的导数 *  旋转矩阵R的转置 这个矩阵 的反对称矩阵 中的 三个量
