### ISSUE TITLE
There is no silence layer in ncnn

### ISSUE THREAD

**Issue by imistyrain** [Ewenwan/MVision#10]
in [mobilenetv2_ssdlite_voc.param](https://github.com/Ewenwan/MVision/blob/master/CNN/HighPerformanceComputing/example/model/mobilenetv2_ssdlite_voc.param) line 152 there is a layer called Silence
Silence          silence
I succeed to run it after replace it with
Slice          slice

**Comment by Ewenwan** [comment]
我这边运行没有问题。
slice layer 作用和concat相反。
silence layer 作用仅仅是避免在log中打印并没有使用的blobs的信息。
ncnn中确实没有 silence layer ，但是我这边没有提示错误。
caffe中有 silence layer 。
