### ISSUE TITLE
请问Ristretto for ssd可以finetune吗?

### ISSUE THREAD

**Issue by HelloSongRen** [Ewenwan/MVision#13]
感谢您的整理，请问这个Ristretto for ssd可以finetune吗?还是只能quantize?

**Comment by Ewenwan** [comment]
可以微调的

**Comment by HelloSongRen** [comment]
我尝试retrain，模型是MobileNet+SSD，但是准确率不升反降，直到0……初始学习率降到0.000001依然这样，请问您有没有什么建议~

**Comment by Ewenwan** [comment]
可以试试把 bias的量化关掉

**Comment by HelloSongRen** [comment]
谢谢您的建议，但是我编译您的Ristretto版本，无法通过，请问这是什么问题呢？

……
                 from src/caffe/data_reader.cpp:8:
./include/caffe/layers/annotated_data_layer.hpp:70:6: note: ‘template<class Dtype> void caffe::DataLayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&)’ previously declared here
 void AnnotatedDataLayer<Dtype>::DataLayerSetUp(
      ^
In file included from src/caffe/data_reader.cpp:8:0:
./include/caffe/layers/annotated_data_layer.hpp:197:6: error: function template-id ‘AnnotatedDataLayer<Dtype>’ in nested-name-specifier
 void AnnotatedDataLayer<Dtype>::load_batch(Batch<Dtype>* batch) {
      ^
./include/caffe/layers/annotated_data_layer.hpp:197:44: error: variable or field ‘load_batch’ declared void
 void AnnotatedDataLayer<Dtype>::load_batch(Batch<Dtype>* batch) {
                                            ^
./include/caffe/layers/annotated_data_layer.hpp:197:44: error: ‘Batch’ was not declared in this scope
./include/caffe/layers/annotated_data_layer.hpp:197:55: error: expected primary-expression before ‘>’ token
 void AnnotatedDataLayer<Dtype>::load_batch(Batch<Dtype>* batch) {
                                                       ^
./include/caffe/layers/annotated_data_layer.hpp:197:58: error: ‘batch’ was not declared in this scope
 void AnnotatedDataLayer<Dtype>::load_batch(Batch<Dtype>* batch) {
                                                          ^
In file included from src/caffe/data_reader.cpp:6:0:
./include/caffe/common.hpp:42:8: error: redefinition of ‘char caffe::gInstantiationGuardAnnotatedDataLayer’
   char gInstantiationGuard##classname; \
        ^
./include/caffe/layers/annotated_data_layer.hpp:477:1: note: in expansion of macro ‘INSTANTIATE_CLASS’
 INSTANTIATE_CLASS(AnnotatedDataLayer);
 ^
./include/caffe/common.hpp:42:8: note: ‘char caffe::gInstantiationGuardAnnotatedDataLayer’ previously declared here
   char gInstantiationGuard##classname; \
        ^
./include/caffe/layers/annotated_data_layer.hpp:477:1: note: in expansion of macro ‘INSTANTIATE_CLASS’
 INSTANTIATE_CLASS(AnnotatedDataLayer);
 ^
./include/caffe/layers/annotated_data_layer.hpp:477:19: error: ‘AnnotatedDataLayer’ is not a class template
 INSTANTIATE_CLASS(AnnotatedDataLayer);
                   ^
./include/caffe/common.hpp:43:18: note: in definition of macro ‘INSTANTIATE_CLASS’
   template class classname<float>; \
                  ^
./include/caffe/layers/annotated_data_layer.hpp:477:19: error: explicit instantiation of non-template type ‘caffe::AnnotatedDataLayer’
 INSTANTIATE_CLASS(AnnotatedDataLayer);
                   ^
./include/caffe/common.hpp:43:18: note: in definition of macro ‘INSTANTIATE_CLASS’
   template class classname<float>; \
                  ^
./include/caffe/layers/annotated_data_layer.hpp:477:19: error: ‘AnnotatedDataLayer’ is not a class template
 INSTANTIATE_CLASS(AnnotatedDataLayer);
                   ^
./include/caffe/common.hpp:44:18: note: in definition of macro ‘INSTANTIATE_CLASS’
   template class classname<double>
                  ^
./include/caffe/layers/annotated_data_layer.hpp:477:19: error: explicit instantiation of non-template type ‘caffe::AnnotatedDataLayer’
 INSTANTIATE_CLASS(AnnotatedDataLayer);
                   ^
./include/caffe/common.hpp:44:18: note: in definition of macro ‘INSTANTIATE_CLASS’
   template class classname<double>
                  ^
In file included from src/caffe/data_reader.cpp:8:0:
./include/caffe/layers/annotated_data_layer.hpp:478:21: error: expected constructor, destructor, or type conversion before ‘(’ token
 REGISTER_LAYER_CLASS(AnnotatedData);
                     ^
Makefile:575: recipe for target '.build_release/src/caffe/data_reader.o' failed
make: *** [.build_release/src/caffe/data_reader.o] Error 1

**Comment by Ewenwan** [comment]
我没有 ristretto 工程啊， 
我这里fork的 ristretto_ssd  https://github.com/Ewenwan/ristretto_ssd 这个支持ssd检测框架，基本上没有修改，你看看原作者的编译有没有问题。
还有一个是最原始的ristretto，只支持分类网络的量化 https://github.com/pmgysel/caffe

**Comment by HelloSongRen** [comment]
嗯嗯，原作者的没问题，我现在在用那个版本。
只是看到您fork的这个有些修改，想试一下看看，但是编译不过，不知道是什么问题……
多谢回复～

**Comment by Ewenwan** [comment]
我修改的就是参考 caffe-yolov2 添加支持 yolov2的量化部分，我之前编译通过的版本没有整体上传，只是修改了哪里，我就在线修改了那些文件夹。
https://github.com/Ewenwan/caffe-yolov2

**Comment by HelloSongRen** [comment]
嗯嗯，谢谢～

我尝试量化我的mobilenetv2-ssd模型，得到这样的结果：
![screenshot from 2018-11-14 15-45-23](https://user-images.githubusercontent.com/32735931/49026086-f118d800-f1d7-11e8-8935-35bc56cb6daf.png)

我感觉有些问题，我理解对activation的量化不应该会造成这么大的精度损失，对权重的逐层量化应该影响更大一些……
这在Google的《Quantizing deep convolutional networks for efficient inference》白皮书里也提到了
![image](https://user-images.githubusercontent.com/32735931/49025997-c6c71a80-f1d7-11e8-9129-59195476d77d.png)
![image](https://user-images.githubusercontent.com/32735931/49026535-0f330800-f1d9-11e8-86b7-db2164d95e5c.png)


您觉得这可能是什么问题呢？难道这个框架的weight和activation弄混了？
谢谢～

**Comment by Ewenwan** [comment]
我看的源码，应该没有搞反。
1. 它统计激活和时是按照绝对值统计的，计算量化参数时，按照正负对成考虑的，所以全为正的激活值在原作者的代码里好像就是一半的精度。
2. 源码也对bias进行了量化，而且使用的量化参数是由统计weight得到的，这里有点不合适，可以不量化bias。
3. 可以只试一下mobilenetv2的量化效果，看和这个带ssd后端的是不是效果一致。

**Comment by huagangxiaoyan666** [comment]
您好，我在使用ristretto对LeNet网络进行动态定点数量化后得到的第一个卷计层的bw_layer_in=8， fl_layer_in=8，我有一个疑问，如果小数部分的位数和整个位宽相同，那么符号位如何表示？没有符号位运算时不正确的，请问这个问题应该怎么解决？

**Comment by huagangxiaoyan666** [comment]
请问使用ristretto对网络进行动态点数量化后，定点化的网络的权值和偏置如何提取？这些信息保存在哪里？

**Comment by Ewenwan** [comment]
1. 定点法:
  a. 量化数转浮点数
   例如 0 1 1 0 1 1 0 1 , FL = 2
   符号位: 0
   尾数部分全部作为整数位： 1 1 0 1 1 0 1 B  = 109D 
   小数部分最后两位，所以整体需要除以2^(2)
   则表示的数为: R = (-1)^0 * 109 * 2^(-2) = 27.25
 
  b. 浮点数 ff  得到量化的数 
   放大/缩小： sff = ff  * 2^(fl) 
   取整：      round(sff) 

2. 动态定点法
   假设量化精度为 B位，
   其中一位符号位s, 
   整数位长度 il = (int)ceil(log2(max(abs(xi)))) 
                      这里输入输出 一般全为正值
                      卷积参数可正可负（会多考虑一位）
   小数位长度 fl = B-il
  
   具体量化方法:
          计算数据范围：
                Dtype max_data = (pow(2, B - 1) - 1) * pow(2, -fl);// 最大数
                Dtype min_data = -pow(2, B - 1) * pow(2, -fl);// 最小数
                其中B-1考虑了一位 符号位
                例如8位精度，4位整数，4位小数
                最大值为 (2^(7)-1)/(2^(4)) = 7.9375
                最小值为 -2^3 = -8
                超过该范围的都将被截断
           截断处理   std::max(std::min(data[index], max_data), min_data) 
           放大           data[index]  *= pow(2, fl)
           取整           round() / floor()
           取整后再缩小获取量化结果  相当于去除了超过小数位的部分
                             data[index] /= pow(2, fl), 存储的时候还是浮点值
                             不过可以按照 定点小数的存储方式进行存储
                             但是源码里 没有处理，保存的模型weight还是浮点数，
                             只不过小数位精度降低了。

**Comment by KaiqiL** [comment]
> 谢谢您的建议，但是我编译您的Ristretto版本，无法通过，请问这是什么问题呢？
> 
> ……
> from src/caffe/data_reader.cpp:8:
> ./include/caffe/layers/annotated_data_layer.hpp:70:6: note: ‘template void caffe::DataLayerSetUp(const std::vector<caffe::Blob_>&, const std::vector<caffe::Blob_>&)’ previously declared here
> void AnnotatedDataLayer::DataLayerSetUp(
> ^
> In file included from src/caffe/data_reader.cpp:8:0:
> ./include/caffe/layers/annotated_data_layer.hpp:197:6: error: function template-id ‘AnnotatedDataLayer’ in nested-name-specifier
> void AnnotatedDataLayer::load_batch(Batch* batch) {
> ^
> ./include/caffe/layers/annotated_data_layer.hpp:197:44: error: variable or field ‘load_batch’ declared void
> void AnnotatedDataLayer::load_batch(Batch* batch) {
> ^
> ./include/caffe/layers/annotated_data_layer.hpp:197:44: error: ‘Batch’ was not declared in this scope
> ./include/caffe/layers/annotated_data_layer.hpp:197:55: error: expected primary-expression before ‘>’ token
> void AnnotatedDataLayer::load_batch(Batch* batch) {
> ^
> ./include/caffe/layers/annotated_data_layer.hpp:197:58: error: ‘batch’ was not declared in this scope
> void AnnotatedDataLayer::load_batch(Batch* batch) {
> ^
> In file included from src/caffe/data_reader.cpp:6:0:
> ./include/caffe/common.hpp:42:8: error: redefinition of ‘char caffe::gInstantiationGuardAnnotatedDataLayer’
> char gInstantiationGuard##classname; 
> ^
> ./include/caffe/layers/annotated_data_layer.hpp:477:1: note: in expansion of macro ‘INSTANTIATE_CLASS’
> INSTANTIATE_CLASS(AnnotatedDataLayer);
> ^
> ./include/caffe/common.hpp:42:8: note: ‘char caffe::gInstantiationGuardAnnotatedDataLayer’ previously declared here
> char gInstantiationGuard##classname; 
> ^
> ./include/caffe/layers/annotated_data_layer.hpp:477:1: note: in expansion of macro ‘INSTANTIATE_CLASS’
> INSTANTIATE_CLASS(AnnotatedDataLayer);
> ^
> ./include/caffe/layers/annotated_data_layer.hpp:477:19: error: ‘AnnotatedDataLayer’ is not a class template
> INSTANTIATE_CLASS(AnnotatedDataLayer);
> ^
> ./include/caffe/common.hpp:43:18: note: in definition of macro ‘INSTANTIATE_CLASS’
> template class classname; 
> ^
> ./include/caffe/layers/annotated_data_layer.hpp:477:19: error: explicit instantiation of non-template type ‘caffe::AnnotatedDataLayer’
> INSTANTIATE_CLASS(AnnotatedDataLayer);
> ^
> ./include/caffe/common.hpp:43:18: note: in definition of macro ‘INSTANTIATE_CLASS’
> template class classname; 
> ^
> ./include/caffe/layers/annotated_data_layer.hpp:477:19: error: ‘AnnotatedDataLayer’ is not a class template
> INSTANTIATE_CLASS(AnnotatedDataLayer);
> ^
> ./include/caffe/common.hpp:44:18: note: in definition of macro ‘INSTANTIATE_CLASS’
> template class classname
> ^
> ./include/caffe/layers/annotated_data_layer.hpp:477:19: error: explicit instantiation of non-template type ‘caffe::AnnotatedDataLayer’
> INSTANTIATE_CLASS(AnnotatedDataLayer);
> ^
> ./include/caffe/common.hpp:44:18: note: in definition of macro ‘INSTANTIATE_CLASS’
> template class classname
> ^
> In file included from src/caffe/data_reader.cpp:8:0:
> ./include/caffe/layers/annotated_data_layer.hpp:478:21: error: expected constructor, destructor, or type conversion before ‘(’ token
> REGISTER_LAYER_CLASS(AnnotatedData);
> ^
> Makefile:575: recipe for target '.build_release/src/caffe/data_reader.o' failed
> make: *** [.build_release/src/caffe/data_reader.o] Error 1

@HelloSongRen  I was facing the same problem when trying to compile it. It seems that you have solved it. Could you suggest how you managed to compile it?

**Comment by honorpeter** [comment]
> 嗯嗯，谢谢～
> 
> 我尝试量化我的mobilenetv2-ssd模型，得到这样的结果：
> ![screenshot from 2018-11-14 15-45-23](https://user-images.githubusercontent.com/32735931/49026086-f118d800-f1d7-11e8-8935-35bc56cb6daf.png)
> 
> 我感觉有些问题，我理解对activation的量化不应该会造成这么大的精度损失，对权重的逐层量化应该影响更大一些……
> 这在Google的《Quantizing deep convolutional networks for efficient inference》白皮书里也提到了
> ![image](https://user-images.githubusercontent.com/32735931/49025997-c6c71a80-f1d7-11e8-9129-59195476d77d.png)
> ![image](https://user-images.githubusercontent.com/32735931/49026535-0f330800-f1d9-11e8-86b7-db2164d95e5c.png)
> 
> 您觉得这可能是什么问题呢？难道这个框架的weight和activation弄混了？
> 谢谢～

@HelloSongRen 
I was facing the same problem when trying to compile it. https://github.com/Ewenwan/MVision/issues/13#issuecomment-446476969
It seems that you have solved it. Could you suggest how you managed to compile it?

**Comment by Scofyyy** [comment]
@HelloSongRen 您好，我在安装作者的ristretto-ssd时也遇到了相同的编译问题，请问您后来是怎么用ristretto量化SSD网络的呢

**Comment by honorpeter** [comment]
早都量化好了，你遇到什么问题了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月6日(星期四) 下午5:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Ewenwan/MVision] 请问Ristretto for ssd可以finetune吗? (#13)





 
@HelloSongRen 您好，我在安装作者的ristretto-ssd时也遇到了相同的编译问题，请问您后来是怎么用ristretto量化SSD网络的呢

**Comment by Scofyyy** [comment]
> 早都量化好了，你遇到什么问题了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年5月6日(星期四) 下午5:01 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Ewenwan/MVision] 请问Ristretto for ssd可以finetune吗? (#13) @HelloSongRen 您好，我在安装作者的ristretto-ssd时也遇到了相同的编译问题，请问您后来是怎么用ristretto量化SSD网络的呢 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
我在安装编译作者提供的ristretto-ssd的时候一直会遇到annotatedDataLayer的错误，相同环境下编译原版的ristretto并没有问题，看这条issue下好像是作者提供的代码有问题？所以想要请教一下您是怎么实现的

**Comment by Scofyyy** [comment]
@honorpeter 我在安装编译作者提供的ristretto-ssd的时候一直会遇到annotatedDataLayer的错误，相同环境下编译原版的ristretto并没有问题，看这条issue下好像是作者提供的代码有问题？所以想要请教一下您是怎么实现的

**Comment by Scofyyy** [comment]
@HelloSongRen 大佬看到了能回一下吗
