### ISSUE TITLE
保存量化后的参数

### ISSUE THREAD

**Issue by huagangxiaoyan666** [Ewenwan/MVision#14]
请问，如何在ristretto的源代码中进行修改，才能将动态定点数量化后的数据保存下来，以便之后的使用？非常感谢

**Comment by Ewenwan** [comment]
如果你选择8位的量化精度，微调中保存的权重数据，已经是量化之后的精度了，不过保存的方式还是 float32，后面读取的时候还需要按 float32，不过数据已经可以用 float8 来表示了，如果要使用 float8来进行计算，得需要支持float8 的机器才行。

**Comment by huagangxiaoyan666** [comment]
非常非常感谢您的解答！
我现在使用的量化策略时动态定点数，量化结束后进行微调，结果显示网络参数为位宽为4bit，fl=3时即可满足精度要求。 之后试图将微调后的生成的 .caffemodel文件中的数据提取出来。提取出的权重显示为[0.24279352,........],以权重为0.24279352为例，转换为定点数后（乘8）得到1.94234816，并不是一个整数，这个情况我无法理解。

我主要的疑问是：原始权重数据为浮点数，量化过程中将权重转化为定点数；然后为适合caffe再次将定点数转换为浮点数，所以最终的浮点数权重与原始浮点数之间有误差（可以理解），但是最终的浮点数与定点数之间应该没有误差。可是从我提出的权重参数来看定点数和最终的浮点数之间也存在误差，这是我不能理解的。或者换句话说，最终的浮点数权重的精度不应该是我提取出来权重精度那么高，小数位为3，最终的浮点数的精度不应该是0.125吗？

我从微调后的网络参数文件.caffemodle中提取权重等参数是按照普通的caffemodel文件提取参数的方法进行，不知道是不是我提取参数的方法不正确导致的问题。

非常感谢您能解答我的问题

**Comment by Ewenwan** [comment]
哦，我想起来了，它微调的过程是这样的:
量化 ->反向传播用浮点梯度更新权重->量化->...
可能是反向传播更新之后就保存了吧

**Comment by huagangxiaoyan666** [comment]
非常感谢您的解答，可是我还是觉得有问题……ristretto这个框架在微调结束后会给出一个对应位宽下的正确率，如果这个正确率是利用在浮点型反向传播更新后的权重进行测试所得到的，那就不能算是定点量化网络，那这个框架的意义又是什么？所以我觉得应该大概可能😂测试的时候用得是限定位宽的权重，这样才有意义.这是我不成熟的小想法.😂😂 再次感谢您的解答！！ liyuliang 邮箱：liyuliang@buaa.edu.cn 签名由 网易邮箱大师 定制 在2018年12月03日 23:51，Wan Youwen 写道： 哦，我想起来了，它微调的过程是这样的: 量化 ->反向传播用浮点梯度更新权重->量化->... 可能是反向传播更新之后就保存了吧 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Ewenwan** [comment]
参考caffe代码框架分析
 https://github.com/Ewenwan/MVision/blob/master/darknect/caffe/readme.md
ristretto 好像对caffe的训练过程没怎么修改，只是添加了几种量化卷积层的实现。
caffe在训练过程中，首先是进行网络的前向传播，后反向传播计算梯度之后，选择SGD等参数更新策略更新，之后根据snapshot的大小间隔保存网络权重。
ristretto 量化后保存的prototxt文件里有每一层的 特征和卷积核的量化参数，网络前向传播的过程中会进入特定的量化层，对数据进行量化，根据网络输出计算损失函数的值之后对梯度进行反向传播再更新参数。
