### ISSUE TITLE
在图片上添加置信值

### ISSUE THREAD

**Issue by MXLHELLO** [Ewenwan/MVision#3]
请问是在src/image.c里的draw_detections函数里添加吗？opencv不太了解，能否指点一下怎么添加

**Comment by Ewenwan** [comment]
void draw_detections() 中， printf("%s: %.0f%%\n", names[j], dets[i].prob[j]*100); (298行) 是命令行显示每种预测的置信度得分，num 是预测出的边框数量，每个边框对每个类别 都会有一个预测概率 dets[i].prob[j]，如果大于阈值的话，标记该预测边框的预测类别，class = j; 后面的代码根据class标记，在图像上imag上直接添加预测的边框和掩码(是直接操作像素值), 后面通过 void show_image()进行显示。

如果需要显示置信度，我觉得有两种解决方案：
1. 类似上面生成标签图像的操作，生成一系列不同大小的0~9，以及小数点的图片，
    在上面的 draw_detections() 中根据 dets[i].prob[j]*100 直接在图像上添加 置信度图像(这里需要解析小数等)。
2. 在函数 draw_detections()中保存一系列，检测边框尺寸位置信息和类别置信度信息(可用vector来保存)，在show_image()中使用 opencv的接口函数在图像上显示字符。
	CvFont font;
	cvInitFont(&font, CV_FONT_HERSHEY_PLAIN, 1.5f, 1.5f, 0, 2, CV_AA);//设置显示的字体
	strID="MyObject";// 显示的文字，这里需要把 float变成字符串
       // cvPoint(P1.x, P1.y-10) 确定文字显示的位置
	cvPutText(pImg,strID, cvPoint(P1.x, P1.y-10), &font, CV_RGB(255, 0, 0));//红色字体注释
