### ISSUE TITLE
关于darnet代码选取的建议

### ISSUE THREAD

**Issue by gangyahaidao** [Ewenwan/MVision#5]
作者你好，看见你整理了这样一个很全的git工程，感觉很是震惊，因为这肯定是长时间研究心得的积累，感谢！
想咨询一下，你的工程中关于darknet部分的代码，既然是整理汇总一些资源，肯定是要选择一些最优的，建议选择这个版本的
https://github.com/AlexeyAB/darknet.git
用他做过一些红外摄像头下的人手识别，感觉比官方的darnet在效果以及资源消耗方面更胜一筹，推荐

**Comment by Ewenwan** [comment]
好的谢谢你啊
