### ISSUE TITLE
视觉定位框架的选取哪种比较稳定可靠呢？

### ISSUE THREAD

**Issue by gangyahaidao** [Ewenwan/MVision#6]
最近打算用摄像头做视觉定位，原来用的是百度研发的一套视觉定位的东西，现在想试一下开源的单目或者双目视觉方案，不知道哪种效果比较好呢？感谢

**Comment by Ewenwan** [comment]
我觉得精度较高的还是 视觉+imu这种自定位的方式，如果是以观察者视角来定位的方式，现在好像还没有比较靠谱的方案(可能是我还没有找到)，以我之前的研究，我觉得是 深度学习目标检测+语义slam的方式，不过这个方案比较耗费资源，inter开源的一个目标定位ros工程，是 mobilenet-ssd目标检测 + 单帧点云来点位，不过感觉精度有点低，可以参考 VSLAM章节。

**Comment by gangyahaidao** [comment]
感谢回复，目前我使用过的开源视觉定位软件就是港科的这个

**Comment by gangyahaidao** [comment]
orb-slam2这个呢，感觉这个目前很多人在用，包括一些以视觉定位为业务的小公司也是基于此开发的产品，你感觉这个怎么样？@Ewenwan

**Comment by Ewenwan** [comment]
百度1200那个性价比真是超高啊，效果很好吗？后面可以买来玩一玩。
如果是 orb-slam2 + imu的话，github也有开源的，之前运行过 orb-slam2，鲁棒性还是不错的，加上imu的话应该会更鲁棒。
orb-slam2 +目标检测+ICP点云配准的定位方式也可以尝试，有一些结合orb-slam2的语义SLAM。

**Comment by gangyahaidao** [comment]
嗯，矫正好之后效果能满足我们现在机器人的定位需求，只是是个商业产品不开源，看具体项目应用了
我在用的过程中发现有两个问题比较关键：
1.静止漂移问题，就是机器人不动定位是否会漂
2.当定位丢失的时候能否快速重新定位

**Comment by sunmiaobo** [comment]
您好，百度的那个双目加imu 的模块在哪里可以买到？供应商是哪家啊？

**Comment by gangyahaidao** [comment]
@sunmiaobo 我是在湖南长沙，找的这个地方代理，你搜搜步科公司联系他们就好了
