### ISSUE TITLE
ref_->T_c_w * T_c_w_estimated_.inverse() 求解的是哪一个坐标转换

### ISSUE THREAD

**Issue by zsustc** [Ewenwan/MVision#8]
https://github.com/Ewenwan/MVision/blob/bb57274fd955b70b4c040ddac9cd4fc1a49b2e8b/vSLAM/ch9project/0.4/src/visual_odometry.cpp#L238

ref_->T_c_w代表是世界坐标系到ref帧相机坐标系的转换T1；
T_c_w_estimated_代表的是ref帧相机坐标系（即curr_的世界坐标系）到curr_相机坐标系的转换T2；

T1*T2代表的是curr_相机坐标系到ref世界坐标系的转换；

T1*T2.inverse()呢，空间上是什么转换？还是说代表了其他含义

**Comment by Ewenwan** [comment]
ref_->T_c_w_ 参考帧坐标系 到 世界坐标系
T_c_w_estimated_ 当前帧坐标系 到 世界坐标系
T_c_w_estimated_.inverse() 世界坐标系 到 当前帧坐标系
ref_->T_c_w_ * T_c_w_estimated_.inverse() 参考帧坐标系 到  当前帧坐标系
